#!/bin/bash

for file in $(find . -name '*.jpg' ! -name 'banner_*.jpg'); 
	do 
		banner_file=`dirname $file`"/banner_"`basename $file` ;

		if [ ! -f $banner_file ]; then
			smartcrop --facedetection --width 1920 --height 800 $file  $(dirname $file)/banner_$(basename $file); 
			echo Created Banner from $file 
		fi

		block_file=`dirname $file`"/block_"`basename $file` ;

		if [ ! -f $block_file ]; then
			smartcrop --facedetection --width 800 --height 600 $file  $(dirname $file)/block_$(basename $file); 
			echo Created Block from $file 
		fi 

	done

